"""
routes/auth.py
---------------
Handles login, logout, and session-based authentication.

Roles (per ClassDiagram.jpg / UseCase.jpg):
    - Citizen      (table: Citizen, PK: citizenId)
    - Administrator (table: Admin,    PK: adminId)

Security notes:
    - All SQL queries use parameterized placeholders (%s) to prevent
      SQL injection.
    - Passwords are compared using werkzeug's hash check. Sample/demo
      records inserted by the SQL script are stored as hashed values
      generated by the same scheme (see municipal_corporation.sql).
"""

from functools import wraps
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from werkzeug.security import check_password_hash
from mysql.connector import Error as MySQLError

from database import get_db_connection

auth_bp = Blueprint("auth", __name__)


# ------------------------------------------------------------------
# Authorization decorators
# ------------------------------------------------------------------
def login_required(f):
    """Blocks access to a route unless a user is logged in (any role)."""
    @wraps(f)
    def decorated(*args, **kwargs):
        if "userId" not in session:
            flash("Please log in to continue.", "error")
            return redirect(url_for("auth.login"))
        return f(*args, **kwargs)
    return decorated


def role_required(role):
    """Blocks access to a route unless the logged-in user has the given role."""
    def decorator(f):
        @wraps(f)
        def decorated(*args, **kwargs):
            if "userId" not in session:
                flash("Please log in to continue.", "error")
                return redirect(url_for("auth.login"))
            if session.get("role") != role:
                flash("You are not authorized to view that page.", "error")
                return redirect(url_for("auth.login"))
            return f(*args, **kwargs)
        return decorated
    return decorator


# ------------------------------------------------------------------
# Routes
# ------------------------------------------------------------------
@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    # If already logged in, skip straight to the right dashboard.
    if "userId" in session:
        if session.get("role") == "citizen":
            return redirect(url_for("citizen.dashboard"))
        elif session.get("role") == "admin":
            return redirect(url_for("admin.dashboard"))

    if request.method == "POST":
        user_id = request.form.get("user_id", "").strip()
        password = request.form.get("password", "").strip()
        role = request.form.get("role", "").strip()

        # ---- Basic validation ----
        if not user_id or not password or not role:
            flash("All fields are required.", "error")
            return render_template("login.html")

        if role not in ("citizen", "admin"):
            flash("Please select a valid role.", "error")
            return render_template("login.html")

        # ---- Authenticate against MySQL ----
        try:
            connection = get_db_connection()
            cursor = connection.cursor(dictionary=True)

            if role == "citizen":
                # citizenId is an INT primary key
                if not user_id.isdigit():
                    flash("Invalid Citizen ID.", "error")
                    return render_template("login.html")

                cursor.execute(
                    "SELECT citizenId, name, password FROM Citizen WHERE citizenId = %s",
                    (int(user_id),)
                )
                user = cursor.fetchone()

                if user and check_password_hash(user["password"], password):
                    session["userId"] = user["citizenId"]
                    session["userName"] = user["name"]
                    session["role"] = "citizen"
                    cursor.close()
                    connection.close()
                    return redirect(url_for("citizen.dashboard"))
                else:
                    flash("Invalid Citizen ID or password.", "error")

            else:  # role == "admin"
                if not user_id.isdigit():
                    flash("Invalid Admin ID.", "error")
                    return render_template("login.html")

                cursor.execute(
                    "SELECT adminId, password FROM Admin WHERE adminId = %s",
                    (int(user_id),)
                )
                user = cursor.fetchone()

                if user and check_password_hash(user["password"], password):
                    session["userId"] = user["adminId"]
                    session["userName"] = f"Admin {user['adminId']}"
                    session["role"] = "admin"
                    cursor.close()
                    connection.close()
                    return redirect(url_for("admin.dashboard"))
                else:
                    flash("Invalid Admin ID or password.", "error")

            cursor.close()
            connection.close()

        except MySQLError:
            # Don't leak DB internals to the user; log server-side in a real deployment.
            flash("Could not connect to the database. Please try again later.", "error")

    return render_template("login.html")


@auth_bp.route("/logout")
def logout():
    session.clear()
    flash("You have been logged out.", "success")
    return redirect(url_for("auth.login"))
